app/main/__init__.py
import logging

logger = logging.getLogger('card-stock')

app/main/routes.py
import json

from requests.exceptions import HTTPError
from flask import Blueprint, render_template, flash, redirect, url_for, session, request, abort
from flask_login import login_required, login_user, current_user, logout_user
from service import card_service
from app import db, login_manager, auth
from app.forms import AddCard, AddCategory
from app.models import CategoryModel, CardModel, UserModel
from requests_oauthlib import OAuth2Session
from . import logger

main_blueprint = Blueprint('main_blueprint', __name__,
                           template_folder='templates', )


@main_blueprint.route('/')
@login_required
def index():
    return render_template('index.html')


@main_blueprint.route('/tracked', methods=['GET'])
@login_required
def watching():
    cards = card_service.CardService().find_listings()
    return render_template('tracked.html', cards=cards, show_more=True)


@main_blueprint.route('/more/<path:card_key>', methods=['GET'])
def see_more(card_key):
    f_card_key = card_key.replace("_", " ")
    cards = card_service.CardService().find_listings_for_card(f_card_key)
    return render_template('tracked.html', cards=cards, show_more=False)


@main_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_to_watched():
    add_category_form = AddCategory()

    choices = CategoryModel.query.with_entities(CategoryModel.ebay_category_id, CategoryModel.ebay_category_name)
    add_card_form = AddCard()
    add_card_form.category_id.choices = choices

    errors = None

    if add_category_form.submit_category.data and add_category_form.validate_on_submit():
        errors = handle_category_form(add_category_form)

        if errors is None:
            return redirect(url_for('main_blueprint.add_to_watched'))
        else:
            logger.error("Form validation for adding category failed - {}".format(errors))

    if add_card_form.submit_card.data and add_card_form.validate_on_submit():
        errors = handle_card_form(add_card_form)

        if errors is None:
            return redirect(url_for('main_blueprint.add_to_watched'))
        else:
            logger.error("Form validation for adding card to track failed; errors={}".format(errors))

    return render_template('add.html', category_form=add_category_form, card_form=add_card_form, errors=errors)


@main_blueprint.route('/login')
def login():
    """
    Handle Login requests
    """

    if current_user.is_authenticated:
        return redirect(url_for('main_blueprint.index'))
    google = get_google_auth()
    auth_url, state = google.authorization_url(
        auth.auth_uri, access_type='offline')
    session['oauth_state'] = state

    return render_template('login.html', auth_url=auth_url)


@main_blueprint.route('/logout')
def logout():
    """
    Log out the user
    """
    logout_user()
    return redirect(url_for('main_blueprint.index'))


@login_manager.user_loader
def load_user(user_id):
    return UserModel.query.get(int(user_id))


@main_blueprint.route('/callback')
def callback():
    """
    Handle OAuth callbacks
    """
    if current_user is not None and current_user.is_authenticated:
        return redirect(url_for('main_blueprint.index'))

    if 'error' in request.args:
        if request.args.get('error') == 'access_denied':
            return 'You denied access.'
        return 'Error encountered.'

    if 'code' not in request.args and 'state' not in request.args:
        return redirect(url_for('main_blueprint.login'))
    else:
        is_authenticated = can_authenticate_user(session)

        if is_authenticated:
            return redirect(url_for('main_blueprint.index'))

        return abort(403)


def can_authenticate_user(user_session):
    """
    Authenticate the user
    """
    is_authenticated = False

    oauth_session = create_oauth2_session(user_session['oauth_state'])
    token = get_oauth_token(oauth_session)

    google_oauth = create_oauth2_session_with_token(token=token)
    resp = google_oauth.get(auth.user_info)

    if resp.status_code == 200:
        is_authenticated = True
        log_user_in(resp, token)

    return is_authenticated


def get_google_auth():
    oauth = OAuth2Session(
        auth.client_id,
        redirect_uri=auth.redirect_uri,
        scope=auth.scope)
    return oauth


def create_oauth2_session(state):
    """
    Creates an OAuth2 session
    """
    return OAuth2Session(auth.client_id, state=state, redirect_uri=auth.redirect_uri)


def get_oauth_token(oauth_session):
    """
    Get Oauth token
    """
    token = None
    try:
        token = oauth_session.fetch_token(auth.token_uri, client_secret=auth.client_secret,
                                          authorization_response=request.url)
        return token
    except HTTPError:
        logger.error("Not able to retrieve Oauth token! response={}", HTTPError.response)
        return token


def create_oauth2_session_with_token(token):
    """
    Authenticate the Oauth token
    """

    return OAuth2Session(auth.client_id, token=token)


def log_user_in(resp, token):
    """
    Logs in the user and updates the database
    """
    user_data = resp.json()
    email = user_data['email']
    user = UserModel.query.filter_by(email=email).first()

    if user is None:
        user = UserModel()
        user.email = email

    user.name = user_data['name']
    user.tokens = json.dumps(token)
    user.avatar = user_data['picture']

    add_item_to_db(user)
    login_user(user)


def handle_category_form(add_category_form):
    """
    Handle POST for category form
    """
    errors = None
    new_id = add_category_form.id.data
    category_name = add_category_form.category_name.data

    existing_category = CategoryModel.query.filter_by(ebay_category_id=new_id).first()

    if existing_category:
        errors = "Category exists in database"
    else:
        new_category = CategoryModel(ebay_category_id=new_id, ebay_category_name=category_name)
        add_item_to_db(new_category)

        flash('Added new category')
        logger.info("Added category to database; category={}".format(category_name))

    return errors


def handle_card_form(add_card_form):
    """
    Handle POST for card form
    """
    errors = None
    category_id = add_card_form.category_id.data
    card = add_card_form.card_name.data

    existing_card = db.session.query(CardModel).filter_by(name=card).first()

    if existing_card:
        errors = "Card exists in database"
    else:
        new_card = CardModel(category_id=category_id, name=card)
        add_item_to_db(new_card)

        flash('Card - {} - added to database'.format(card))
        logger.info("Added category to database; card={}".format(card))

    return errors


# noinspection PyMethodMayBeStatic
def add_item_to_db(item):
    """
    Adds the item to the database
    """

    db.session.add(item)
    db.session.commit()

app/main/templates/add.html
{% extends 'layout.html' %}

{% block content %}

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
            <div class="uk-alert-success" uk-alert>
                <a class="uk-alert-close" uk-close></a>
                <p>{{ message }}</p>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% if errors %}
    <div class="uk-alert-danger" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p>{{ errors }}</p>
    </div>
    {% endif %}

    {% include 'add_category_form.html' %}
    {% include 'add_card_form.html' %}
{% endblock %}

app/main/templates/add_card_form.html
<div class="uk-section">
        <div class="uk-container uk-container-small">
            <form class="uk-form-horizontal uk-margin-large" action="" method="POST">
                <fieldset class="uk-fieldset">
                    <legend class="uk-legend">Add new card</legend>
                     {{ card_form.hidden_tag() }}
                    <div class="uk-margin">
                         {{ card_form.category_id.label(class_="uk-form-label") }}
                        <div class="uk-form-controls">
                            {{ card_form.category_id(class_="uk-select uk-form-width-medium") }}
                        </div>
                    </div>

                    {% if card_form.category_id.errors %}
                     <div class="uk-margin">
                         <ul class="uk-list">
                         {% for error in card_form.category_id.errors  %}
                            <li>{{ error }}</li>
                         {% endfor %}
                        </ul>
                     </div>
                    {% endif %}

                    <div class="uk-margin">
                         {{ card_form.card_name.label(class_="uk-form-label") }}
                        <div class="uk-form-controls">
                            {{ card_form.card_name(class_="uk-select uk-form-width-medium") }}
                        </div>
                    </div>

                    {% if card_form.card_name.errors %}
                     <div class="uk-margin">
                         <ul class="uk-list">
                         {% for error in card_form.card_name.errors  %}
                            <li>{{ error }}</li>
                         {% endfor %}
                        </ul>
                     </div>
                    {% endif %}


                    <div class="uk-margin">
                        {{ card_form.submit_card(class_="uk-button uk-button-default") }}
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

app/main/templates/add_category_form.html
<div class="uk-section">
        <div class="uk-container uk-container-small">
            <form class="uk-form-horizontal uk-margin-large" action="" method="POST">
                <fieldset class="uk-fieldset">
                    <legend class="uk-legend">Add new category</legend>
                    {{ category_form.hidden_tag() }}
                    <div class="uk-margin">
                         {{ category_form.id.label(class_="uk-form-label") }}
                        <div class="uk-form-controls">
                            {{ category_form.id(class_="uk-input uk-form-width-medium", size=16) }}
                        </div>
                    </div>

                    {% if category_form.id.errors %}
                     <div class="uk-margin">
                         <ul class="uk-list">
                         {% for error in category_form.id.errors  %}
                            <li>{{ error }}</li>
                         {% endfor %}
                        </ul>
                     </div>
                    {% endif %}

                    <div class="uk-margin">
                         {{ category_form.category_name.label(class_="uk-form-label") }}
                        <div class="uk-form-controls">
                            {{ category_form.category_name(class_="uk-input uk-form-width-medium", size=16) }}
                        </div>
                    </div>

                    {% if category_form.id.errors %}
                     <div class="uk-margin">
                         <ul class="uk-list">
                         {% for error in category_form.category_name.errors  %}
                            <li>{{ error }}</li>
                         {% endfor %}
                        </ul>
                     </div>
                    {% endif %}

                    <div class="uk-margin">
                        {{ category_form.submit_category(class_="uk-button uk-button-default") }}
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

app/main/templates/index.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

app/main/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.3.7/dist/css/uikit.min.css" />

</head>
<body>
    <div class="uk-container uk-container-large">
        {% if current_user.is_authenticated %}
            {% include 'nav_bar.html' %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.7/dist/js/uikit-icons.min.js"></script>

</body>
</html>

app/main/templates/login.html
{% extends 'layout.html' %}

{% block content %}

<div class="uk-position-center">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
            <div uk-alert>
                <a class="uk-alert-close" uk-close></a>
                <h3>Notice</h3>
                <p>{{ message }}</p>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <a href="{{auth_url}}" class="uk-button uk-button-primary uk-button-large">Login with Google</a>
</div>
{% endblock %}

app/main/templates/nav_bar.html
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="{{ url_for('main_blueprint.add_to_watched') }}">Add Items</a></li>
            <li><a href="{{ url_for('main_blueprint.watching') }}">Tracked Items</a></li>
        </ul>
    </div>
    <div class="uk-navbar-right">

        <ul class="uk-navbar-nav">
            <li><a href="{{ url_for('main_blueprint.logout') }}">Logout</a></li>
        </ul>
    </div>
</nav>

app/main/templates/tracked.html
{% extends 'layout.html' %}

{% block content %}

    <div class="uk-overflow-auto">
        <table class="uk-table uk-table-hover uk-table-middle uk-table-divider">
            <thead>
                <tr>
                    <th class="uk-table-shrink"></th>
                    <th class="uk-table-shrink uk-text-nowrap">Image</th>
                    <th class="uk-table-shrink">Card</th>
                    <th class="uk-table-shrink">Price + Shipping</th>
                    <th class="uk-table-shrink">Auction Type</th>
                    {% if show_more %}
                        <th class="uk-table-shrink">See More</th>
                    {% endif %}
                    <th class="uk-table-shrink">Listing</th>
                </tr>
            </thead>
            <tbody>
    {% for card in cards %}
                <tr>
                    <td><input class="uk-checkbox" type="checkbox"></td>
                    <td>
                        <img class="uk-preserve-width uk-border-circle" src="{{ card.image }}" width="40" alt="">
                    </td>
                    <td class="uk-text-nowrap">
                        {{ card.title }}
                    </td>
                    <td class="uk-text-nowrap">
                        ${{ card.price }} + {{ card.shipping }}
                    </td>
                    <td class="uk-text-nowrap">
                        {{ card.listing_type }}
                    </td>
                    {% if show_more %}
                        <td class="">
                            {% if card.found_listing %}
                                <a class="uk-button uk-button-default" href="/more/{{ card.key|replace(' ', '_') }}"
                                   target="_blank">See More</a>
                            {% else %}
                                <p>No listing found</p>
                            {% endif %}
                        </td>
                    {% endif %}
                    <td class="">
                        {% if card.found_listing %}
                            <a class="uk-button uk-button-default" href="{{ card.url }}" target="_blank">See Listing</a>
                        {% else %}
                            <p>No listing found</p>
                        {% endif %}
                    </td>
                </tr>
    {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}